package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateRFSComponentResourceBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String crossId;
	private Boolean primary;

	public CreateRFSComponentResourceBody() {
	}

	public String getCrossId() {
		return this.crossId;
	}

	public void setCrossId( String crossId) {
		this.crossId = crossId;
	}

	public Boolean getPrimary() {
		return this.primary;
	}

	public void setPrimary( Boolean primary) {
		this.primary = primary;
	}

	public CreateRFSComponentResourceBody( String crossId,
                                           Boolean primary) {
		this.crossId = crossId;
		this.primary = primary;
	}

}