package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateServiceBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String name;
	private String serviceType;
	private String serviceStatus;

	public CreateServiceBody() {
	}

	public String getName() {
		return this.name;
	}

	public void setName( String name) {
		this.name = name;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType( String serviceType) {
		this.serviceType = serviceType;
	}

	public String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus( String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public CreateServiceBody( String name,
                              String serviceType, String serviceStatus) {
		this.name = name;
		this.serviceType = serviceType;
		this.serviceStatus = serviceStatus;
	}

}