package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateProjectBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String creator;
	private java.lang.String status;
	private java.lang.String projectTypeDiscriminator;

	private java.lang.String nodePlannedStatusDiscriminator;

	private java.lang.String linkPlannedStatusDiscriminator;

	private java.lang.String rfsPlannedStatusDiscriminator;

	private java.lang.String rfscPlannedStatusDiscriminator;

	private java.lang.Boolean autoPlannedStatus;

	public CreateProjectBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getCreator() {
		return this.creator;
	}

	public void setCreator(java.lang.String creator) {
		this.creator = creator;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getProjectTypeDiscriminator() {
		return this.projectTypeDiscriminator;
	}

	public void setProjectTypeDiscriminator(
			java.lang.String projectTypeDiscriminator) {
		this.projectTypeDiscriminator = projectTypeDiscriminator;
	}

	public java.lang.String getNodePlannedStatusDiscriminator() {
		return this.nodePlannedStatusDiscriminator;
	}

	public void setNodePlannedStatusDiscriminator(
			java.lang.String nodePlannedStatusDiscriminator) {
		this.nodePlannedStatusDiscriminator = nodePlannedStatusDiscriminator;
	}

	public java.lang.String getLinkPlannedStatusDiscriminator() {
		return this.linkPlannedStatusDiscriminator;
	}

	public void setLinkPlannedStatusDiscriminator(
			java.lang.String linkPlannedStatusDiscriminator) {
		this.linkPlannedStatusDiscriminator = linkPlannedStatusDiscriminator;
	}

	public java.lang.String getRfsPlannedStatusDiscriminator() {
		return this.rfsPlannedStatusDiscriminator;
	}

	public void setRfsPlannedStatusDiscriminator(
			java.lang.String rfsPlannedStatusDiscriminator) {
		this.rfsPlannedStatusDiscriminator = rfsPlannedStatusDiscriminator;
	}

	public java.lang.String getRfscPlannedStatusDiscriminator() {
		return this.rfscPlannedStatusDiscriminator;
	}

	public void setRfscPlannedStatusDiscriminator(
			java.lang.String rfscPlannedStatusDiscriminator) {
		this.rfscPlannedStatusDiscriminator = rfscPlannedStatusDiscriminator;
	}

	public java.lang.Boolean getAutoPlannedStatus() {
		return this.autoPlannedStatus;
	}

	public void setAutoPlannedStatus(java.lang.Boolean autoPlannedStatus) {
		this.autoPlannedStatus = autoPlannedStatus;
	}

	public CreateProjectBody(java.lang.String name, java.lang.String creator,
			java.lang.String status, java.lang.String projectTypeDiscriminator,
			java.lang.String nodePlannedStatusDiscriminator,
			java.lang.String linkPlannedStatusDiscriminator,
			java.lang.String rfsPlannedStatusDiscriminator,
			java.lang.String rfscPlannedStatusDiscriminator,
			java.lang.Boolean autoPlannedStatus) {
		this.name = name;
		this.creator = creator;
		this.status = status;
		this.projectTypeDiscriminator = projectTypeDiscriminator;
		this.nodePlannedStatusDiscriminator = nodePlannedStatusDiscriminator;
		this.linkPlannedStatusDiscriminator = linkPlannedStatusDiscriminator;
		this.rfsPlannedStatusDiscriminator = rfsPlannedStatusDiscriminator;
		this.rfscPlannedStatusDiscriminator = rfscPlannedStatusDiscriminator;
		this.autoPlannedStatus = autoPlannedStatus;
	}

}