package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateServiceFromServiceTemplateBody
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String serviceTemplateName;
	private java.lang.String name;

	public CreateServiceFromServiceTemplateBody() {
	}

	public java.lang.String getServiceTemplateName() {
		return this.serviceTemplateName;
	}

	public void setServiceTemplateName(java.lang.String serviceTemplateName) {
		this.serviceTemplateName = serviceTemplateName;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public CreateServiceFromServiceTemplateBody(
			java.lang.String serviceTemplateName, java.lang.String name) {
		this.serviceTemplateName = serviceTemplateName;
		this.name = name;
	}

}