package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateServiceBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String serviceType;
	private java.lang.String serviceStatus;

	public CreateServiceBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.String getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(java.lang.String serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	public CreateServiceBody(java.lang.String name,
			java.lang.String serviceType, java.lang.String serviceStatus) {
		this.name = name;
		this.serviceType = serviceType;
		this.serviceStatus = serviceStatus;
	}

}