package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateRFSComponentBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.cross.CreateRFSComponentResourceBody> resources;

	public CreateRFSComponentBody() {
	}

	public java.util.List<com.cross.CreateRFSComponentResourceBody> getResources() {
		return this.resources;
	}

	public void setResources(
			java.util.List<com.cross.CreateRFSComponentResourceBody> resources) {
		this.resources = resources;
	}

	public CreateRFSComponentBody(
			java.util.List<com.cross.CreateRFSComponentResourceBody> resources) {
		this.resources = resources;
	}

}