package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateLinkBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String description;
	private java.lang.Integer capacityFull;
	private java.lang.String routingPolicy;
	private java.lang.Integer mainFibrilCount;
	private java.lang.Integer protectionFibrilCount;
	private java.lang.String status;
	private java.lang.String linkType;
	private java.lang.String startNode;
	private java.lang.String endNode;

	private java.util.List<com.cross.CreateLinkProviderBody> providers;

	public CreateLinkBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getCapacityFull() {
		return this.capacityFull;
	}

	public void setCapacityFull(java.lang.Integer capacityFull) {
		this.capacityFull = capacityFull;
	}

	public java.lang.String getRoutingPolicy() {
		return this.routingPolicy;
	}

	public void setRoutingPolicy(java.lang.String routingPolicy) {
		this.routingPolicy = routingPolicy;
	}

	public java.lang.Integer getMainFibrilCount() {
		return this.mainFibrilCount;
	}

	public void setMainFibrilCount(java.lang.Integer mainFibrilCount) {
		this.mainFibrilCount = mainFibrilCount;
	}

	public java.lang.Integer getProtectionFibrilCount() {
		return this.protectionFibrilCount;
	}

	public void setProtectionFibrilCount(java.lang.Integer protectionFibrilCount) {
		this.protectionFibrilCount = protectionFibrilCount;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getLinkType() {
		return this.linkType;
	}

	public void setLinkType(java.lang.String linkType) {
		this.linkType = linkType;
	}

	public java.lang.String getStartNode() {
		return this.startNode;
	}

	public void setStartNode(java.lang.String startNode) {
		this.startNode = startNode;
	}

	public java.lang.String getEndNode() {
		return this.endNode;
	}

	public void setEndNode(java.lang.String endNode) {
		this.endNode = endNode;
	}

	public java.util.List<com.cross.CreateLinkProviderBody> getProviders() {
		return this.providers;
	}

	public void setProviders(
			java.util.List<com.cross.CreateLinkProviderBody> providers) {
		this.providers = providers;
	}

	public CreateLinkBody(java.lang.String name, java.lang.String description,
			java.lang.Integer capacityFull, java.lang.String routingPolicy,
			java.lang.Integer mainFibrilCount,
			java.lang.Integer protectionFibrilCount, java.lang.String status,
			java.lang.String linkType, java.lang.String startNode,
			java.lang.String endNode,
			java.util.List<com.cross.CreateLinkProviderBody> providers) {
		this.name = name;
		this.description = description;
		this.capacityFull = capacityFull;
		this.routingPolicy = routingPolicy;
		this.mainFibrilCount = mainFibrilCount;
		this.protectionFibrilCount = protectionFibrilCount;
		this.status = status;
		this.linkType = linkType;
		this.startNode = startNode;
		this.endNode = endNode;
		this.providers = providers;
	}

}