package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateRFSComponentResourceBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String crossId;
	private java.lang.Boolean primary;

	public CreateRFSComponentResourceBody() {
	}

	public java.lang.String getCrossId() {
		return this.crossId;
	}

	public void setCrossId(java.lang.String crossId) {
		this.crossId = crossId;
	}

	public java.lang.Boolean getPrimary() {
		return this.primary;
	}

	public void setPrimary(java.lang.Boolean primary) {
		this.primary = primary;
	}

	public CreateRFSComponentResourceBody(java.lang.String crossId,
			java.lang.Boolean primary) {
		this.crossId = crossId;
		this.primary = primary;
	}

}