package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreateNodeBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String statusDiscriminator;
	private java.util.List<java.lang.String> parentCrossIds;
	private java.util.List<java.lang.String> nodeTypeDiscriminators;
	private java.lang.String geometry;
	private java.lang.Boolean inheritedGeometry;

	private java.util.List<com.cross.CustomAttributeBody> customAttributes;

	public CreateNodeBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getStatusDiscriminator() {
		return this.statusDiscriminator;
	}

	public void setStatusDiscriminator(java.lang.String statusDiscriminator) {
		this.statusDiscriminator = statusDiscriminator;
	}

	public java.util.List<java.lang.String> getParentCrossIds() {
		return this.parentCrossIds;
	}

	public void setParentCrossIds(
			java.util.List<java.lang.String> parentCrossIds) {
		this.parentCrossIds = parentCrossIds;
	}

	public java.util.List<java.lang.String> getNodeTypeDiscriminators() {
		return this.nodeTypeDiscriminators;
	}

	public void setNodeTypeDiscriminators(
			java.util.List<java.lang.String> nodeTypeDiscriminators) {
		this.nodeTypeDiscriminators = nodeTypeDiscriminators;
	}

	public java.lang.String getGeometry() {
		return this.geometry;
	}

	public void setGeometry(java.lang.String geometry) {
		this.geometry = geometry;
	}

	public java.lang.Boolean getInheritedGeometry() {
		return this.inheritedGeometry;
	}

	public void setInheritedGeometry(java.lang.Boolean inheritedGeometry) {
		this.inheritedGeometry = inheritedGeometry;
	}

	public java.util.List<com.cross.CustomAttributeBody> getCustomAttributes() {
		return this.customAttributes;
	}

	public void setCustomAttributes(
			java.util.List<com.cross.CustomAttributeBody> customAttributes) {
		this.customAttributes = customAttributes;
	}

	public CreateNodeBody(java.lang.String name,
			java.lang.String statusDiscriminator,
			java.util.List<java.lang.String> parentCrossIds,
			java.util.List<java.lang.String> nodeTypeDiscriminators,
			java.lang.String geometry, java.lang.Boolean inheritedGeometry,
			java.util.List<com.cross.CustomAttributeBody> customAttributes) {
		this.name = name;
		this.statusDiscriminator = statusDiscriminator;
		this.parentCrossIds = parentCrossIds;
		this.nodeTypeDiscriminators = nodeTypeDiscriminators;
		this.geometry = geometry;
		this.inheritedGeometry = inheritedGeometry;
		this.customAttributes = customAttributes;
	}

}