package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomAttributeBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.util.List<com.cross.CustomAttributeValBody> val;

	public CustomAttributeBody() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<com.cross.CustomAttributeValBody> getVal() {
		return this.val;
	}

	public void setVal(java.util.List<com.cross.CustomAttributeValBody> val) {
		this.val = val;
	}

	public CustomAttributeBody(java.lang.String name,
			java.util.List<com.cross.CustomAttributeValBody> val) {
		this.name = name;
		this.val = val;
	}

}