package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomAttributeValBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String externalId;
	private java.lang.String systemId;

	public CustomAttributeValBody() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(java.lang.String externalId) {
		this.externalId = externalId;
	}

	public java.lang.String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(java.lang.String systemId) {
		this.systemId = systemId;
	}

	public CustomAttributeValBody(java.lang.String type,
			java.lang.String externalId, java.lang.String systemId) {
		this.type = type;
		this.externalId = externalId;
		this.systemId = systemId;
	}

}