package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomAttributeBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String name;

	private java.util.List<CustomAttributeValBody> val;

	public CustomAttributeBody() {
	}

	public String getName() {
		return this.name;
	}

	public void setName( String name) {
		this.name = name;
	}

	public java.util.List<CustomAttributeValBody> getVal() {
		return this.val;
	}

	public void setVal(java.util.List<CustomAttributeValBody> val) {
		this.val = val;
	}

	public CustomAttributeBody( String name,
                                java.util.List<CustomAttributeValBody> val) {
		this.name = name;
		this.val = val;
	}

}