package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExactSearchBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String entity;
	private String entityFilterExpression;
	private java.util.List<com.cross.ExactSearchJoinBody> joins;
	private java.util.List<com.cross.ExactSearchAttributeBody> select;
	private java.util.List<com.cross.ExactSearchAttributeBody> orderBy;
	private java.lang.Boolean returnTotalCount;

	private java.lang.Integer limit;

	public ExactSearchBody() {
	}

	public java.lang.String getEntity() {
		return this.entity;
	}

	public void setEntity(java.lang.String entity) {
		this.entity = entity;
	}

	public java.util.List<com.cross.ExactSearchJoinBody> getJoins() {
		return this.joins;
	}

	public void setJoins(java.util.List<com.cross.ExactSearchJoinBody> joins) {
		this.joins = joins;
	}

	public java.util.List<com.cross.ExactSearchAttributeBody> getSelect() {
		return this.select;
	}

	public void setSelect(
			java.util.List<com.cross.ExactSearchAttributeBody> select) {
		this.select = select;
	}

	public java.util.List<com.cross.ExactSearchAttributeBody> getOrderBy() {
		return this.orderBy;
	}

	public void setOrderBy(
			java.util.List<com.cross.ExactSearchAttributeBody> orderBy) {
		this.orderBy = orderBy;
	}

	public java.lang.Boolean getReturnTotalCount() {
		return this.returnTotalCount;
	}

	public void setReturnTotalCount(java.lang.Boolean returnTotalCount) {
		this.returnTotalCount = returnTotalCount;
	}

	public java.lang.String getEntityFilterExpression() {
		return this.entityFilterExpression;
	}

	public void setEntityFilterExpression(
			java.lang.String entityFilterExpression) {
		this.entityFilterExpression = entityFilterExpression;
	}

	public java.lang.Integer getLimit() {
		return this.limit;
	}

	public void setLimit(java.lang.Integer limit) {
		this.limit = limit;
	}

	public ExactSearchBody(java.lang.String entity,
			java.lang.String entityFilterExpression,
			java.util.List<com.cross.ExactSearchJoinBody> joins,
			java.util.List<com.cross.ExactSearchAttributeBody> select,
			java.util.List<com.cross.ExactSearchAttributeBody> orderBy,
			java.lang.Boolean returnTotalCount, java.lang.Integer limit) {
		this.entity = entity;
		this.entityFilterExpression = entityFilterExpression;
		this.joins = joins;
		this.select = select;
		this.orderBy = orderBy;
		this.returnTotalCount = returnTotalCount;
		this.limit = limit;
	}

}