package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExactSearchJoinBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String leftRelation;
	private java.lang.String rightRelation;
	private java.lang.String filterExpression;
	private java.lang.Boolean useLeftJoin;

	public ExactSearchJoinBody() {
	}

	public java.lang.String getLeftRelation() {
		return this.leftRelation;
	}

	public void setLeftRelation(java.lang.String leftRelation) {
		this.leftRelation = leftRelation;
	}

	public java.lang.String getRightRelation() {
		return this.rightRelation;
	}

	public void setRightRelation(java.lang.String rightRelation) {
		this.rightRelation = rightRelation;
	}

	public java.lang.String getFilterExpression() {
		return this.filterExpression;
	}

	public void setFilterExpression(java.lang.String filterExpression) {
		this.filterExpression = filterExpression;
	}

	public java.lang.Boolean getUseLeftJoin() {
		return this.useLeftJoin;
	}

	public void setUseLeftJoin(java.lang.Boolean useLeftJoin) {
		this.useLeftJoin = useLeftJoin;
	}

	public ExactSearchJoinBody(java.lang.String leftRelation,
			java.lang.String rightRelation, java.lang.String filterExpression,
			java.lang.Boolean useLeftJoin) {
		this.leftRelation = leftRelation;
		this.rightRelation = rightRelation;
		this.filterExpression = filterExpression;
		this.useLeftJoin = useLeftJoin;
	}

}