package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExactSearchAttributeBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String relationName;
	private String attributeName;

	public ExactSearchAttributeBody() {
	}

	public String getRelationName() {
		return this.relationName;
	}

	public void setRelationName( String relationName) {
		this.relationName = relationName;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName( String attributeName) {
		this.attributeName = attributeName;
	}

	public ExactSearchAttributeBody( String relationName,
                                     String attributeName) {
		this.relationName = relationName;
		this.attributeName = attributeName;
	}

}