package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotifyEventBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Notification type")
	private String type;
	@org.kie.api.definition.type.Label("Notification event state")
	private String state;
	@org.kie.api.definition.type.Label("Name of the project")
	private String projectName;
	@org.kie.api.definition.type.Label("Resource facing service CROSS ID")
	private String rfsCrossId;
	@org.kie.api.definition.type.Label("Name of the allocated PE port")
	private String pePortName;

	private NotifyErrorMessageBody error;

	public NotifyEventBody() {
	}

	public String getType() {
		return this.type;
	}

	public void setType( String type) {
		this.type = type;
	}

	public String getState() {
		return this.state;
	}

	public void setState( String state) {
		this.state = state;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName( String projectName) {
		this.projectName = projectName;
	}

	public String getRfsCrossId() {
		return this.rfsCrossId;
	}

	public void setRfsCrossId( String rfsCrossId) {
		this.rfsCrossId = rfsCrossId;
	}

	public String getPePortName() {
		return this.pePortName;
	}

	public void setPePortName( String pePortName) {
		this.pePortName = pePortName;
	}

	public NotifyErrorMessageBody getError() {
		return this.error;
	}

	public void setError( NotifyErrorMessageBody error) {
		this.error = error;
	}

	public NotifyEventBody( String type, String state,
                            String projectName, String rfsCrossId,
                            String pePortName, NotifyErrorMessageBody error) {
		this.type = type;
		this.state = state;
		this.projectName = projectName;
		this.rfsCrossId = rfsCrossId;
		this.pePortName = pePortName;
		this.error = error;
	}

}