package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotifyServiceOrderBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String id;
	private com.cross.NotifyErrorMessageBody errorMessage;
	private java.lang.String state;
	private java.lang.String pePortName;
	private java.lang.String rfsCrossId;

	public NotifyServiceOrderBody() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public com.cross.NotifyErrorMessageBody getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(com.cross.NotifyErrorMessageBody errorMessage) {
		this.errorMessage = errorMessage;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getPePortName() {
		return this.pePortName;
	}

	public void setPePortName( java.lang.String pePortName) {
		this.pePortName = pePortName;
	}

	public java.lang.String getRfsCrossId() {
		return this.rfsCrossId;
	}

	public void setRfsCrossId( java.lang.String rfsCrossId) {
		this.rfsCrossId = rfsCrossId;
	}

	public NotifyServiceOrderBody(java.lang.String type, java.lang.String id,
								  com.cross.NotifyErrorMessageBody errorMessage,
								  java.lang.String state, java.lang.String pePortName,
								  java.lang.String rfsCrossId) {
		this.type = type;
		this.id = id;
		this.errorMessage = errorMessage;
		this.state = state;
		this.pePortName = pePortName;
		this.rfsCrossId = rfsCrossId;
	}

}