package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotifyServiceOrderCreateEventBody implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private NotifyServiceOrderBody event;
    private String eventType;

    private String type;

    public NotifyServiceOrderCreateEventBody( NotifyServiceOrderBody event, String eventType, String type ) {
        this.event = event;
        this.eventType = eventType;
        this.type = type;
    }

    public NotifyServiceOrderBody getEvent() {
        return this.event;
    }

    public void setEvent( NotifyServiceOrderBody event ) {
        this.event = event;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType( String eventType ) {
        this.eventType = eventType;
    }

    public String getType() {
        return this.type;
    }

    public void setType( String type ) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "NotifyServiceOrderCreateEventBody{" + "event=" + event + ", eventType='" + eventType + '\'' + ", type='" + type + '\'' + '}';
    }

}
