package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotifyServiceOrderCreateEventBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.cross.NotifyServiceOrderBody event;
	private java.lang.String eventType;

	private java.lang.String type;

	public NotifyServiceOrderCreateEventBody() {
	}

	public com.cross.NotifyServiceOrderBody getEvent() {
		return this.event;
	}

	public void setEvent(com.cross.NotifyServiceOrderBody event) {
		this.event = event;
	}

	public java.lang.String getEventType() {
		return this.eventType;
	}

	public void setEventType(java.lang.String eventType) {
		this.eventType = eventType;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public NotifyServiceOrderCreateEventBody(
			com.cross.NotifyServiceOrderBody event, java.lang.String eventType,
			java.lang.String type) {
		this.event = event;
		this.eventType = eventType;
		this.type = type;
	}

}