package com.cross;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NotifyErrorMessageBody implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String code;
	private java.lang.String message;
	private java.lang.String reason;

	public NotifyErrorMessageBody() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public NotifyErrorMessageBody(java.lang.String type, java.lang.String code,
			java.lang.String message, java.lang.String reason) {
		this.type = type;
		this.code = code;
		this.message = message;
		this.reason = reason;
	}

}